import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import { createProject } from '../src/create.js';
import { doctor } from '../src/doctor.js';
import { cleanDemo } from '../src/clean-demo.js';
import { printAgentBrief } from '../src/brief.js';

test('create scaffolds an Expo-first nativepilot app', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-create-'));
  const root = path.join(temp, 'PilotApp');
  const result = await createProject('PilotApp', { dir: root, providers: 'openai,local' });
  assert.equal(result.root, root);
  assert.ok(result.files.includes('app/chat.tsx'));
  assert.ok(result.files.includes('src/ai/client.ts'));
  const manifest = JSON.parse(await readFile(path.join(root, 'nativepilot.manifest.json'), 'utf8'));
  assert.equal(manifest.generator, 'nativepilot');
  assert.deepEqual(manifest.providers, ['openai', 'local']);
  const readme = await readFile(path.join(root, 'README.md'), 'utf8');
  assert.match(readme, /Generated by nativepilot/);
  assert.match(readme, /OpenAI-compatible/);
  const pkg = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
  assert.equal(pkg.dependencies.expo, '~57.0.8');
  assert.equal(pkg.dependencies.react, '19.2.3');
  assert.equal(pkg.dependencies['react-native'], '0.86.2');
  assert.equal(pkg.dependencies['react-native-reanimated'], '4.5.1');
  assert.equal(pkg.dependencies['react-native-worklets'], '0.10.1');
  assert.equal(pkg.devDependencies.typescript, '~6.0.3');
  assert.equal(pkg.scripts.typecheck, 'tsc --noEmit');
  assert.equal(pkg.scripts.doctor, 'expo-doctor');
});


test('create accepts an explicit filesystem path as target', async () => {
  const base = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-path-'));
  const target = path.join(base, 'PathSmoke');
  const result = await createProject(target, { providers: 'local' });
  assert.equal(result.root, target);
  const pkg = JSON.parse(await readFile(path.join(target, 'package.json'), 'utf8'));
  assert.equal(pkg.name, 'pathsmoke');
});

test('doctor passes a fresh generated app', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-doctor-'));
  await createProject('DoctorApp', { dir: temp });
  const result = await doctor(temp, ['unsafe-key', 'stale-guidance']);
  assert.equal(result.ok, true, JSON.stringify(result.issues));
  assert.equal(result.issues.some((issue) => issue.code === 'missing-script'), false);
});

test('doctor catches unsafe provider keys', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-key-'));
  await createProject('KeyApp', { dir: temp });
  await writeFile(path.join(temp, 'src/ai/leak.ts'), 'export const key = "sk-abcdefghijklmnopqrstuvwxyz123456";\n');
  const result = await doctor(temp);
  assert.equal(result.ok, false);
  assert.ok(result.issues.some((issue) => issue.code === 'unsafe-key'));
});

test('doctor reports malformed and invalid manifest metadata as structured issues', async () => {
  for (const [label, value] of [
    ['malformed', '{broken'],
    ['array', '[]'],
    ['invalid-fields', JSON.stringify({ generator: 1, preset: null, demoState: [], managedPaths: 'app' })],
  ] as const) {
    const temp = await mkdtemp(path.join(os.tmpdir(), `nativepilot-manifest-${label}-`));
    await createProject('ManifestApp', { dir: temp });
    await writeFile(path.join(temp, 'nativepilot.manifest.json'), value);
    const result = await doctor(temp);
    assert.equal(result.ok, false);
    assert.ok(result.issues.some((issue) => issue.code === 'invalid-manifest'
      && issue.severity === 'error'
      && issue.file === 'nativepilot.manifest.json'), JSON.stringify(result.issues));
  }
});

test('doctor reports an unreadable manifest path as a file-specific issue', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-manifest-unreadable-'));
  await createProject('UnreadableManifestApp', { dir: temp });
  await rm(path.join(temp, 'nativepilot.manifest.json'));
  await mkdir(path.join(temp, 'nativepilot.manifest.json'));

  const result = await doctor(temp);

  assert.equal(result.ok, false);
  assert.ok(result.issues.some((issue) => issue.code === 'invalid-manifest'
    && issue.file === 'nativepilot.manifest.json'
    && /Unable to read/.test(issue.message)), JSON.stringify(result.issues));
});

test('clean-demo removes showcase while preserving AI wiring', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-clean-'));
  await createProject('CleanApp', { dir: temp });
  const result = await cleanDemo(temp);
  assert.deepEqual(result.removed, ['app/chat.tsx', 'src/demo']);
  const audit = await readFile(path.join(temp, 'docs/DEMO_REMOVED.md'), 'utf8');
  assert.match(audit, /showcase chat screen was removed/);
  const client = await readFile(path.join(temp, 'src/ai/client.ts'), 'utf8');
  assert.match(client, /AIProviderConfig/);
  const manifest = JSON.parse(await readFile(path.join(temp, 'nativepilot.manifest.json'), 'utf8'));
  assert.equal(manifest.demoState, 'removed');
});

test('clean-demo rejects malformed metadata without partially mutating the project', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-clean-invalid-'));
  await createProject('InvalidCleanApp', { dir: temp });
  const tracked = ['app/chat.tsx', 'src/demo/demoContent.ts', 'app/index.tsx', 'nativepilot.manifest.json'];
  await writeFile(path.join(temp, 'nativepilot.manifest.json'), '{broken');
  const before = new Map(await Promise.all(tracked.map(async (file) => [file, await readFile(path.join(temp, file), 'utf8')] as const)));

  await assert.rejects(cleanDemo(temp), /Malformed JSON.*nativepilot\.manifest\.json/);

  for (const file of tracked) assert.equal(await readFile(path.join(temp, file), 'utf8'), before.get(file));
  await assert.rejects(readFile(path.join(temp, 'docs/DEMO_REMOVED.md'), 'utf8'), { code: 'ENOENT' });
});

test('CLI clean-demo exits nonzero without mutation for invalid manifest shapes', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-clean-shape-'));
  await createProject('ShapeCleanApp', { dir: temp });
  await writeFile(path.join(temp, 'nativepilot.manifest.json'), '[]');
  const chatBefore = await readFile(path.join(temp, 'app/chat.tsx'), 'utf8');
  const cli = path.resolve('dist/src/index.js');

  const result = spawnSync(process.execPath, [cli, 'clean-demo', temp], { encoding: 'utf8' });

  assert.equal(result.status, 1, result.stderr || result.stdout);
  assert.match(result.stderr, /must contain a JSON object/);
  assert.equal(await readFile(path.join(temp, 'app/chat.tsx'), 'utf8'), chatBefore);
  assert.equal(await readFile(path.join(temp, 'nativepilot.manifest.json'), 'utf8'), '[]');
  assert.match(await readFile(path.join(temp, 'src/demo/demoContent.ts'), 'utf8'), /demoPrompts/);
  await assert.rejects(readFile(path.join(temp, 'docs/DEMO_REMOVED.md'), 'utf8'), { code: 'ENOENT' });
});

test('CLI doctor passes before and after the supported clean-demo lifecycle', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-lifecycle-'));
  const root = path.join(temp, 'LifecycleApp');
  const cli = path.resolve('dist/src/index.js');
  const run = (...args: string[]) => spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
  assert.equal(run('create', 'LifecycleApp', '--dir', root).status, 0);
  const before = run('doctor', root);
  assert.equal(before.status, 0, before.stderr || before.stdout);
  assert.equal(run('clean-demo', root).status, 0);
  const after = run('doctor', root);
  assert.equal(after.status, 0, after.stderr || after.stdout);
});

test('CLI distinguishes omitted providers from empty provider input', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-provider-cli-'));
  const cli = path.resolve('dist/src/index.js');
  const run = (...args: string[]) => spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });

  const omittedRoot = path.join(temp, 'OmittedProviders');
  const omitted = run('create', 'OmittedProviders', '--dir', omittedRoot);
  assert.equal(omitted.status, 0, omitted.stderr || omitted.stdout);
  assert.deepEqual(JSON.parse(await readFile(path.join(omittedRoot, 'nativepilot.manifest.json'), 'utf8')).providers,
    ['openai', 'anthropic', 'gemini', 'local']);

  for (const [label, value] of [['empty', ''], ['whitespace', '   '], ['commas', ',,,']] as const) {
    const root = path.join(temp, label);
    const result = run('create', label, '--dir', root, '--providers', value);
    assert.equal(result.status, 1, result.stderr || result.stdout);
    assert.match(result.stderr, /cannot be empty.*openai,anthropic,gemini,local/i);
  }
});

test('doctor rejects an unmarked project with a missing chat screen', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-missing-chat-'));
  await createProject('MissingChatApp', { dir: temp });
  await rm(path.join(temp, 'app/chat.tsx'));
  const result = await doctor(temp);
  assert.equal(result.ok, false);
  assert.ok(result.issues.some((issue) => issue.code === 'missing-file' && issue.file === 'app/chat.tsx'));
});

test('print-agent-brief includes verification and safety boundaries', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-brief-'));
  await createProject('BriefApp', { dir: temp });
  const brief = await printAgentBrief(temp, 'codex');
  assert.match(brief, /server\/proxy/);
  assert.match(brief, /nativepilot doctor/);
});
