import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createProject } from '../src/create.js';
import { doctor } from '../src/doctor.js';
import { cleanDemo } from '../src/clean-demo.js';
import { printAgentBrief } from '../src/brief.js';

test('create scaffolds an Expo-first nativepilot app', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-create-'));
  const root = path.join(temp, 'PilotApp');
  const result = await createProject('PilotApp', { dir: root, providers: 'openai,local' });
  assert.equal(result.root, root);
  assert.ok(result.files.includes('app/chat.tsx'));
  assert.ok(result.files.includes('src/ai/client.ts'));
  const readme = await readFile(path.join(root, 'README.md'), 'utf8');
  assert.match(readme, /Generated by nativepilot/);
  assert.match(readme, /OpenAI-compatible/);
});

test('doctor passes a fresh generated app', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-doctor-'));
  await createProject('DoctorApp', { dir: temp });
  const result = await doctor(temp, ['unsafe-key', 'stale-guidance']);
  assert.equal(result.ok, true, JSON.stringify(result.issues));
});

test('doctor catches unsafe provider keys', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-key-'));
  await createProject('KeyApp', { dir: temp });
  await writeFile(path.join(temp, 'src/ai/leak.ts'), 'export const key = "sk-abcdefghijklmnopqrstuvwxyz123456";\n');
  const result = await doctor(temp);
  assert.equal(result.ok, false);
  assert.ok(result.issues.some((issue) => issue.code === 'unsafe-key'));
});

test('clean-demo removes showcase while preserving AI wiring', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-clean-'));
  await createProject('CleanApp', { dir: temp });
  const result = await cleanDemo(temp);
  assert.deepEqual(result.removed, ['app/chat.tsx', 'src/demo']);
  const client = await readFile(path.join(temp, 'src/ai/client.ts'), 'utf8');
  assert.match(client, /AIProviderConfig/);
});

test('print-agent-brief includes verification and safety boundaries', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-brief-'));
  await createProject('BriefApp', { dir: temp });
  const brief = await printAgentBrief(temp, 'codex');
  assert.match(brief, /server\/proxy/);
  assert.match(brief, /nativepilot doctor/);
});
