import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import { createProject } from '../src/create.js';
import { doctor } from '../src/doctor.js';
import { cleanDemo } from '../src/clean-demo.js';
import { printAgentBrief } from '../src/brief.js';

test('create scaffolds an Expo-first nativepilot app', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-create-'));
  const root = path.join(temp, 'PilotApp');
  const result = await createProject('PilotApp', { dir: root, providers: 'openai,local' });
  assert.equal(result.root, root);
  assert.ok(result.files.includes('app/chat.tsx'));
  assert.ok(result.files.includes('src/ai/client.ts'));
  const manifest = JSON.parse(await readFile(path.join(root, 'nativepilot.manifest.json'), 'utf8'));
  assert.equal(manifest.generator, 'nativepilot');
  assert.deepEqual(manifest.providers, ['openai', 'local']);
  const readme = await readFile(path.join(root, 'README.md'), 'utf8');
  assert.match(readme, /Generated by nativepilot/);
  assert.match(readme, /OpenAI-compatible/);
  const pkg = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
  assert.equal(pkg.dependencies.expo, '~57.0.8');
  assert.equal(pkg.dependencies.react, '19.2.3');
  assert.equal(pkg.dependencies['react-native'], '0.86.2');
  assert.equal(pkg.dependencies['react-native-reanimated'], '4.5.1');
  assert.equal(pkg.dependencies['react-native-worklets'], '0.10.1');
  assert.equal(pkg.devDependencies.typescript, '~6.0.3');
  assert.equal(pkg.scripts.typecheck, 'tsc --noEmit');
  assert.equal(pkg.scripts.doctor, 'expo-doctor');
});


test('create accepts an explicit filesystem path as target', async () => {
  const base = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-path-'));
  const target = path.join(base, 'PathSmoke');
  const result = await createProject(target, { providers: 'local' });
  assert.equal(result.root, target);
  const pkg = JSON.parse(await readFile(path.join(target, 'package.json'), 'utf8'));
  assert.equal(pkg.name, 'pathsmoke');
});

test('doctor passes a fresh generated app', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-doctor-'));
  await createProject('DoctorApp', { dir: temp });
  const result = await doctor(temp, ['unsafe-key', 'stale-guidance']);
  assert.equal(result.ok, true, JSON.stringify(result.issues));
  assert.equal(result.issues.some((issue) => issue.code === 'missing-script'), false);
});

test('doctor catches unsafe provider keys', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-key-'));
  await createProject('KeyApp', { dir: temp });
  await writeFile(path.join(temp, 'src/ai/leak.ts'), 'export const key = "sk-abcdefghijklmnopqrstuvwxyz123456";\n');
  const result = await doctor(temp);
  assert.equal(result.ok, false);
  assert.ok(result.issues.some((issue) => issue.code === 'unsafe-key'));
});

test('clean-demo removes showcase while preserving AI wiring', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-clean-'));
  await createProject('CleanApp', { dir: temp });
  const result = await cleanDemo(temp);
  assert.deepEqual(result.removed, ['app/chat.tsx', 'src/demo']);
  const audit = await readFile(path.join(temp, 'docs/DEMO_REMOVED.md'), 'utf8');
  assert.match(audit, /showcase chat screen was removed/);
  const client = await readFile(path.join(temp, 'src/ai/client.ts'), 'utf8');
  assert.match(client, /AIProviderConfig/);
  const manifest = JSON.parse(await readFile(path.join(temp, 'nativepilot.manifest.json'), 'utf8'));
  assert.equal(manifest.demoState, 'removed');
});

test('CLI doctor passes before and after the supported clean-demo lifecycle', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-lifecycle-'));
  const root = path.join(temp, 'LifecycleApp');
  const cli = path.resolve('dist/src/index.js');
  const run = (...args: string[]) => spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
  assert.equal(run('create', 'LifecycleApp', '--dir', root).status, 0);
  const before = run('doctor', root);
  assert.equal(before.status, 0, before.stderr || before.stdout);
  assert.equal(run('clean-demo', root).status, 0);
  const after = run('doctor', root);
  assert.equal(after.status, 0, after.stderr || after.stdout);
});

test('doctor rejects an unmarked project with a missing chat screen', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-missing-chat-'));
  await createProject('MissingChatApp', { dir: temp });
  await rm(path.join(temp, 'app/chat.tsx'));
  const result = await doctor(temp);
  assert.equal(result.ok, false);
  assert.ok(result.issues.some((issue) => issue.code === 'missing-file' && issue.file === 'app/chat.tsx'));
});

test('print-agent-brief includes verification and safety boundaries', async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'nativepilot-brief-'));
  await createProject('BriefApp', { dir: temp });
  const brief = await printAgentBrief(temp, 'codex');
  assert.match(brief, /server\/proxy/);
  assert.match(brief, /nativepilot doctor/);
});
